site_name: CLU Documentation
site_url: https://clucomics.org
theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - social:
      enabled: true

repo_url: https://github.com/allaboutduncan/comic-utils

nav:
  - Home: index.md
  - Getting Started:
    - Quickstart: getting-started/quickstart.md
    - Navigating the App: getting-started/publish-your-docs.md
    - Configuring the App: getting-started/publish-your-docs-1.md
  - Features:
    - Overview: features/index.md
    - ComicVine: features/comicvine.md
    - Collection: features/collection.md
    - Directory Features:
      - Introduction: features/directory-features/index.md
      - Clean All Filenames: features/directory-features/editor.md
      - Convert Directory: features/directory-features/markdown.md
      - Rebuild All Files: features/directory-features/markdown-1.md
      - Convert PDF to CBZ: features/directory-features/markdown-2.md
      - Missing Issue Check: features/directory-features/markdown-3.md
      - Enhance Images: features/directory-features/markdown-4.md
      - Clean ComicInfo.xml: features/directory-features/markdown-5.md
      - App Logs: features/directory-features/integrations.md
    - Single File Features:
      - Introduction: features/single-file-features/index.md
      - Edit CBZ File: features/single-file-features/editor.md
      - Single File Rebuild: features/single-file-features/editor-1.md
      - Crop Cover: features/single-file-features/editor-2.md
      - Remove First Image: features/single-file-features/editor-3.md
      - Add blank Image: features/single-file-features/editor-4.md
      - Enhance Images: features/single-file-features/editor-5.md
      - Delete File: features/single-file-features/editor-6.md
    - File Downloads:
      - Introduction: features/file-downloads/index.md
      - Chrome Extension: features/file-downloads/editor.md
      - Right-Click to Download: features/file-downloads/editor-1.md
      - Download Status Page: features/file-downloads/editor-2.md
    - File Management:
      - Introduction: features/file-management/index.md
      - Move: features/file-management/editor.md
      - Rename: features/file-management/editor-1.md
      - Delete: features/file-management/editor-2.md
      - Additional Features: features/file-management/editor-3.md
      - Generate ComicInfo.xml: features/file-management/editor-2-1.md
    - Folder Monitoring:
      - Introduction: features/folder-monitoring/index.md
      - Monitoring Setup: features/folder-monitoring/integrations.md
      - Features: features/folder-monitoring/integrations-1.md
      - Monitoring Logs: features/folder-monitoring/integrations-2.md
    - App Settings:
      - Introduction: features/app-settings/index.md
      - Config Installation: features/app-settings/integrations.md
      - Settings Available: features/app-settings/integrations-1.md
    - GCD Database Support:
      - Introduction: features/app-settings-1/index.md
      - GCD Database Download: features/app-settings-1/integrations.md
      - MySQL Database Setup: features/app-settings-1/integrations-1.md
      - Updated CLU Settings for GCD: features/app-settings-1/integrations-1-1.md
  - FAQ: frequently-asked-questions.md
  - CLU Discord: https://discord.com/channels/678794935368941569/1349564970609938553


# This tells MkDocs your markdown files are in the root or a 'docs' subfolder.
# If your files are in the root, you don't need 'docs_dir'.
# If they are in a folder named 'docs', MkDocs finds them automatically.
