site_name: CLU Documentation
site_url: https://clucomics.org
site_description: "The ultimate self-hosted comic book library manager. Edit CBZ files, manage your filesystem, and download from Metron & GetComics. A powerful alternative to Komga and Kavita."
site_author: "CLU Team"
copyright: "Copyright &copy; 2024 CLU"

theme:
  name: material
  logo: assets/clu.png
  favicon: assets/clu.png
  palette: 
    scheme: default      # Forces Light Mode
    primary: indigo      # Your primary color
    accent: deep purple  # Your accent color
  features:
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css

plugins:
  - search
  - social:
      enabled: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

repo_url: https://github.com/allaboutduncan/comic-utils

nav:
  - Home: index.md
  - Why CLU?: why-clu.md
  - Getting Started:
    - Quickstart: getting-started/quickstart.md
    - Navigating the App: getting-started/navigate.md

  - Collection Features:
    - features/collection/index.md
    - Publishers: features/collection/publishers.md
    - Series: features/collection/series.md
    - Issues: features/collection/issues.md
    - Reading: features/collection/reading.md

  - Directory Features:
    - features/directory-features/index.md
    - Clean All Filenames: features/directory-features/rename.md
    - Convert Directory: features/directory-features/convert.md
    - Rebuild All Files: features/directory-features/rebuild.md
    - Convert PDF to CBZ: features/directory-features/pdf.md
    - Missing Issue Check: features/directory-features/missing.md
    - Enhance Images: features/directory-features/enhance.md
    - Clean ComicInfo.xml: features/directory-features/clean.md
  
  - Single File Features:
    - features/single-file-features/index.md
    - Edit CBZ File: features/single-file-features/edit.md
    - Single File Rebuild: features/single-file-features/rebuild.md
    - Crop Cover: features/single-file-features/crop.md
    - Remove First Image: features/single-file-features/remove.md
    - Add blank Image: features/single-file-features/add.md
    - Enhance Images: features/single-file-features/enhance.md
    - Read Date: features/single-file-features/date.md
    - Delete File: features/single-file-features/delete.md

  - Folder Monitoring:
    - features/folder-monitoring/index.md
    - Monitoring Setup: features/folder-monitoring/setup.md
    - Features: features/folder-monitoring/features.md
    - Monitoring Logs: features/folder-monitoring/logs.md

  - File Downloads:
    - features/file-downloads/index.md
    - Chrome Extension: features/file-downloads/setup.md
    - Click to Download: features/file-downloads/send.md
    - Download Status Page: features/file-downloads/status.md
  
  - File Management:
    - features/file-management/index.md
    - Move: features/file-management/move.md
    - Rename: features/file-management/rename.md
    - Delete: features/file-management/delete.md
    - Additional Features: features/file-management/additional.md
    - Get ComicInfo.xml: features/file-management/comicinfo.md
    - Comicvine Metadata: features/file-management/comicvine.md
    - Metron Metadata: features/file-management/metron.md
  
  - Library Insights:
    - features/insights/index.md
    - Library Insights Page: features/insights/insights.md
    - Insights API: features/insights/api.md
    - Timeline: features/insights/timeline.md

  - Pull List:
    - features/pull-list/index.md
    - Releases: features/pull-list/releases.md
    - Series: features/pull-list/series.md
    - Pull List: features/pull-list/pull-list.md
    - Wanted: features/pull-list/wanted.md
    - Series Search: features/pull-list/series-search.md
    - Publishers: features/pull-list/publishers.md

  - App Settings:
    - features/app-settings/index.md
    - Config Installation: features/app-settings/install.md
    - File Processing Settings: features/app-settings/file-settings.md
    - Download & API Settings: features/app-settings/download-settings.md
    - System Settings: features/app-settings/system-settings.md
    - Styling: features/app-settings/styling.md
    - App Logs: features/app-settings/logs.md
  
  - GCD Database Support:
    - features/gcd-settings/index.md
    - GCD Database Download: features/gcd-settings/download.md
    - MySQL Database Setup: features/gcd-settings/setup.md
    - Updated CLU Settings for GCD: features/gcd-settings/settings.md
  
  - FAQ: frequently-asked-questions.md
  - CLU Discord: https://discord.gg/ndDhpvrgBa


# This tells MkDocs your markdown files are in the root or a 'docs' subfolder.
# If your files are in the root, you don't need 'docs_dir'.
# If they are in a folder named 'docs', MkDocs finds them automatically.
