site_name: CLU Documentation
site_url: https://clucomics.org
theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css

plugins:
  - search
  - social:
      enabled: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

repo_url: https://github.com/allaboutduncan/comic-utils

nav:
  - Home: index.md
  - Getting Started:
    - Quickstart: getting-started/quickstart.md
    - Navigating the App: getting-started/navigate.md
  - Features:
    - Overview: features/index.md
    - ComicVine: features/comicvine.md
    - Collection Features:
      - Introduction: features/collection/index.md
      - Publishers: features/collection/publishers.md
      - Series: features/collection/series.md
      - Issues: features/collection/issues.md
    - Directory Features:
      - Introduction: features/directory-features/index.md
      - Clean All Filenames: features/directory-features/rename.md
      - Convert Directory: features/directory-features/convert.md
      - Rebuild All Files: features/directory-features/rebuild.md
      - Convert PDF to CBZ: features/directory-features/pdf.md
      - Missing Issue Check: features/directory-features/missing.md
      - Enhance Images: features/directory-features/enhance.md
      - Clean ComicInfo.xml: features/directory-features/clean.md
      - App Logs: features/directory-features/logs.md
    - Single File Features:
      - Introduction: features/single-file-features/index.md
      - Edit CBZ File: features/single-file-features/edit.md
      - Single File Rebuild: features/single-file-features/rebuild.md
      - Crop Cover: features/single-file-features/crop.md
      - Remove First Image: features/single-file-features/remove.md
      - Add blank Image: features/single-file-features/add.md
      - Enhance Images: features/single-file-features/enhance.md
      - Delete File: features/single-file-features/delete.md
    - File Downloads:
      - Introduction: features/file-downloads/index.md
      - Chrome Extension: features/file-downloads/setup.md
      - Right-Click to Download: features/file-downloads/send.md
      - Download Status Page: features/file-downloads/status.md
    - File Management:
      - Introduction: features/file-management/index.md
      - Move: features/file-management/move.md
      - Rename: features/file-management/rename.md
      - Delete: features/file-management/delete.md
      - Additional Features: features/file-management/additional.md
      - Generate ComicInfo.xml: features/file-management/comicinfo.md
    - Folder Monitoring:
      - Introduction: features/folder-monitoring/index.md
      - Monitoring Setup: features/folder-monitoring/setup.md
      - Features: features/folder-monitoring/features.md
      - Monitoring Logs: features/folder-monitoring/logs.md
    - App Settings:
      - Introduction: features/app-settings/index.md
      - Config Installation: features/app-settings/install.md
      - Settings Available: features/app-settings/settings.md
    - GCD Database Support:
      - Introduction: features/gcd-settings/index.md
      - GCD Database Download: features/gcd-settings/download.md
      - MySQL Database Setup: features/gcd-settings/setup.md
      - Updated CLU Settings for GCD: features/gcd-settings/settings.md
  - FAQ: frequently-asked-questions.md
  - CLU Discord: https://discord.com/channels/678794935368941569/1349564970609938553


# This tells MkDocs your markdown files are in the root or a 'docs' subfolder.
# If your files are in the root, you don't need 'docs_dir'.
# If they are in a folder named 'docs', MkDocs finds them automatically.
